jobs:
  my-job:
    docker:
    - image: circleci/python:3-stretch-browsers
    steps:
      - aws-parameter-store/load
      - checkout
orbs:
  aws-parameter-store: circleci/aws-parameter-store@1.0.0
version: 2.1
workflows:
  build_and_test:
    jobs:
      - my-job
  version: 2
  